POST http://localhost:4000/blocks/add
Content-Type: application/json

{
    "id": 3,
    "hash": "dummyblock2",
    "previousHash": "yzx",
    "nonce": 3,
    "timestamp": "01.07.2020",
    "transactions": []
    
}

###
POST http://localhost:4000/blocks/update/6009c7018776244d7cad4789
Content-Type: application/json

{
    "id": 2,
    "hash": "dummyblock2",
    "previousHash": "yzx",
    "nonce": 3,
    "timestamp": "01.07.2020",
    "transactions": {
        "to": "xxx",
        "from": "xxxx",
        "amount": "x"
    }
    
}
###
POST http://localhost:4000/users/add
Content-Type: application/json

{
    "publicKey": "ccc",
    "privateKey": "nananan",
    "balance" : ""
}


###

GET http://localhost:4000/users


###
GET http://localhost:4000/users/